### ISSUE TITLE
Getting nan loss for a custom dataset 

### ISSUE THREAD

**Issue by SumayyaInayat** [wangchen1801/FPD#1]
Hi Zichen Wang,
I hope you are well.
You have done a wonderful job.The idea is great and thanks alot for sharing the code. 

I have two custom datasets and I trained the model for one, giving me good mAP but when train on another, it is giving nan losses after 50 iterations.

Both the datasets are relatively similar except for the object sizes, in the first one, object size are small as compared to the standard voc dataset objects. I got results for this dataset.

While in another, object sizes are of medium size. But I am getting nan loss. The bounding boxes are correct.

If you can help or guide me in this, it would be great.

Thanks & Regards!
Sumayya

**Comment by wangchen1801** [comment]
Thank you for your interest in this work!
To fit a custom dataset, we should change the following configs. Please ensure the custom dataset has been configured properly.
* configs/fpd/voc/split1/fpd_r101_c4_2xb4_voc-split1_10shot-fine-tuning.py
```python
data = dict(
    train=dict(
        num_support_ways=21,  # total number of classes
        dataset=dict(
            ann_cfg=[dict(method='MetaRCNN', setting='SPLIT4_10SHOT'),  # custom class split
                     dict(type='ann_file', ann_file=data_root + 'dataset_path/custom_train.txt')],
            classes='ALL_CLASSES_SPLIT4',
        )),
    val=dict(classes='ALL_CLASSES_SPLIT4'),
    test=dict(classes='ALL_CLASSES_SPLIT4'),
    model_init=dict(classes='ALL_CLASSES_SPLIT4'))

model = dict(
    roi_head=dict(num_novel=6,  # number of novel classes
                  prototypes_distillation=dict(num_novel=6),
                  bbox_head=dict(num_classes=21, num_meta_classes=21),
                  novel_class=(15, 16, 17, 18, 19, 20),  # indices of novel classes
                  )
)
```
* mmfewshot/mmfewshot/detection/datasets/voc.py
```python
VOC_SPLIT = dict(
    # custom class split
    ALL_CLASSES_SPLIT4=('bicycle', 'bird', 'boat', 'bus', 'car', 'cat',
                         'chair', 'diningtable', 'dog', 'motorbike', 'person',
                         'pottedplant', 'sheep', 'train', 'tvmonitor',
                         'novel_1', 'novel_2', 'novel_3', 'novel_4', 'novel_5', 'novel_6'),
    NOVEL_CLASSES_SPLIT4=('novel_1', 'novel_2', 'novel_3', 'novel_4', 'novel_5', 'novel_6'),
    BASE_CLASSES_SPLIT4=('bicycle', 'bird', 'boat', 'bus', 'car', 'cat',
                         'chair', 'diningtable', 'dog', 'motorbike', 'person',
                         'pottedplant', 'sheep', 'train', 'tvmonitor')
)

class FewShotVOCDefaultDataset(FewShotVOCDataset):
    # register the custom dataset
    voc_benchmark.update(
        {
            f'SPLIT{split}_{shot}SHOT': [
                dict(
                    type='ann_file',
                    ann_file=f'data/VOCdevkit/Aerial/few_shot_ann/custom_{shot}shot/'
                             f'box_{shot}shot_{class_name}_train.txt',
                    ann_classes=[class_name])
                for class_name in VOC_SPLIT[f'ALL_CLASSES_SPLIT{split}']
            ]
            for shot in [10, 30, 50] for split in [4, ]
        }
    )
```
Moreover, please check for any file corruption issue and ensure that the imgs are being read correctly. And inspect annotations in your second dataset to ensure that they are correctly formatted. Corrupted imgs and incorrect labels could lead to unexpected behavior during training.

Let me know if you have any further questions!

**Comment by SumayyaInayat** [comment]
Thanks for helping.
I figured out. Few labels were missing.
Thanks& Regards!
