### ISSUE TITLE
lr error nan

### ISSUE THREAD

**Issue by lydcv** [wangchen1801/FPD#12]
Good job! Hello friend, I would like to ask if I can use a single 3090GPU to learn with a learning rate of 0.0025. Sometimes, suddenly, there is an issue. I noticed that the code you provided is 2 * 3090 with an lr of 0.005, while the one provided in the paper is 0.004. May I ask which specific lr you implemented.

**Comment by wangchen1801** [comment]
Hello, please use the same configuration as in this repository to reproduce the result, otherwise it may not achieve the reported accuracy. And the learning rate should also following the code. Thanks~

**Comment by lydcv** [comment]
> 您好，请使用与此存储库中相同的配置来重现结果，否则可能无法达到报告的准确性。并且学习率也应该遵循代码。谢谢~

Thanks for your reply!
