### ISSUE TITLE
Visualization issues

### ISSUE THREAD

**Issue by wml666666** [wangchen1801/FPD#13]
Hello, based on the code and training weights you provided (Voc Novel Set1 10shot), I visualized the results similar to Figure 10 in the appendix of your paper, but the visualization results were not satisfactory. May I ask if this is a normal phenomenon or if there are errors in some of my steps!
![VOC2007000001_2_assigned_prototypes](https://github.com/wangchen1801/FPD/assets/45289402/f3902c91-f0a3-4372-98df-aed2bfca4f85)
![VOC2007000002_2_assigned_prototypes](https://github.com/wangchen1801/FPD/assets/45289402/3a05d549-dadc-41b4-9351-c588510853cd)
![image](https://github.com/wangchen1801/FPD/assets/45289402/e73a3a29-3f5f-4f3e-8f4a-48d300c84730)

**Comment by wangchen1801** [comment]
Hello, please refer to the code in [issue#8](https://github.com/wangchen1801/FPD/issues/8) to see if it helps.
Normally, you need to set the parameter 'num_bg' to 0 and retrain the model in order to reproduce the results, otherwise this visualization method will become ineffective.

**Comment by wml666666** [comment]
> Hello, please refer to the code in [issue#8](https://github.com/wangchen1801/FPD/issues/8) to see if it helps. Normally, you need to set the parameter 'num_bg' to 0 and retrain the model in order to reproduce the results, otherwise this visualization method will become ineffective.

I'm very sorry for neglecting the point you mentioned. I apologize for disturbing you and thank you for your reply amidst your busy schedule!
