### ISSUE TITLE
为什么要将骨干网络提取特征分为stage1-3和stage4呢？

### ISSUE THREAD

**Issue by wanganjin** [wangchen1801/FPD#18]
作者您好！我最近在学习基于元学习的小样本目标检测相关的研究，对您的这个研究很感兴趣，我阅读了您的文章和代码，但有一点不太明白，就是您代码中为为什么要将骨干网络提取特征分为stage1-3和stage4呢？相较于直接在FFA模块之前就用骨干网络提取stage4的特征或者stage5的特征会有什么不同呢？这样做是否提升了模型的性能？作为初学者的我对此感到十分好奇，非常希望能得到您的回复，万分感谢！

**Comment by wangchen1801** [comment]
您好，stage 4后面特征图维度高，尺寸小（比如1x1x2048），基本不包含细节特征，可以这么理解。

---- 回复的原邮件 ----
| 发件人 | Anjin ***@***.***> |
| 发送日期 | 2024年10月20日 17:40 |
| 收件人 | wangchen1801/FPD ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [wangchen1801/FPD] 为什么要将骨干网络提取特征分为stage1-3和stage4呢？ (Issue #18) |

作者您好！我最近在学习基于元学习的小样本目标检测相关的研究，对您的这个研究很感兴趣，我阅读了您的文章和代码，但有一点不太明白，就是您代码中为为什么要将骨干网络提取特征分为stage1-3和stage4呢？相较于直接在FFA模块之前就用骨干网络提取stage4的特征或者stage5的特征会有什么不同呢？这样做是否提升了模型的性能？作为初学者的我对此感到十分好奇，非常希望能得到您的回复，万分感谢！

**Comment by wanganjin** [comment]
非常感谢您的解答！我尝试在代码中找到模型上半部分和下半部分使用resnet stage4提取高级特征部分的代码，但是我始终没找到这一部分的代码。
代码中这部分提及了reslayer4（fpd_roi_head.py），但恕我眼拙，具体是哪几行代码使用了resnet stage4我并没有看出来，还希望您能再指点一二，期待您的回复！
![image](https://github.com/user-attachments/assets/e00ec6e0-5588-4f53-aaa9-6e971ae016ca)

**Comment by wangchen1801** [comment]
- reslayer4：self.extract_query_roi_feat()
```python
  query_roi_feats = self.extract_query_roi_feat([fused_feats], query_rois) # reslayer4
  rpt_prototype = support_feat[supp_order]

  # roi_align, reslayer4, bbox_head, loss_func
  for k in range(num_supp_per_im):
      start, end = k * batch_size, (k + 1) * batch_size
      prototype = [item.unsqueeze(0).expand(len_query_roi, -1) for item, len_query_roi in
                   zip(rpt_prototype[start:end], len_query_rois)]
      prototype = torch.concat(prototype)  # (512, 2048)
```
- You can find this function below. It takes feature maps as input. And output roi features with shape (N, C).
<img width="550" alt="截屏2024-10-21 21 54 46" src="https://github.com/user-attachments/assets/b6a6d25c-f9ab-4607-8075-5fa60ff8b599">

**Comment by wanganjin** [comment]
十分感谢！再次感谢您的耐心解答！
