### ISSUE TITLE
How to reproduce the "average results over multiple runs"?

### ISSUE THREAD

**Issue by FrankLeeCode** [wangchen1801/FPD#5]
To my understanding, the "Average results over multiple runs" are derived from utilizing 30 distinct sample seeds, as demonstrated in the [data split](http://dl.yf.io/fs-det/datasets/vocsplit/). However, upon examining the re-organized data split, I noticed only one seed annotation provided (as indicated [here](https://github.com/open-mmlab/mmfewshot/blob/main/tools/data/detection/voc/README.md)). Consequently, I can only obtain results from a single run. How can I replicate the process to achieve the "Average results over multiple runs"?

**Comment by wangchen1801** [comment]
Thank you for your interest in our work!
Currently, mmfewshot only support one fixed few shot dataset. To evaluate the samples generate from different seeds, we can replace the .txt in benchmark_[K]shot mannuly, and modify the img path, for example: 
```angular
datasets/VOC2012/JPEGImages/2008_006761.jpg -> VOC2012/JPEGImages/2008_006761.jpg 
```
We can also register the different samples into FewShotVOCDataset in mmfewshot/mmfewshot/detection/datasets/voc.py, as the following code:
```python
    voc_benchmark = {
        f'SPLIT{split}_{shot}SHOT': [
            dict(
                type='ann_file',
                ann_file=f'data/few_shot_ann/voc/benchmark_{shot}shot/'
                f'box_{shot}shot_{class_name}_train.txt',
                ann_classes=[class_name])
            for class_name in VOC_SPLIT[f'ALL_CLASSES_SPLIT{split}']
        ]
        for shot in [1, 2, 3, 5, 10] for split in [1, 2, 3]
    }
```

**Comment by FrankLeeCode** [comment]
Thank you for your prompt response! I truly appreciate it. Your explanation has resolved my query perfectly.
