### ISSUE TITLE
transformers.py

### ISSUE THREAD

**Issue by yefeng23323** [wangchen1801/FPD#9]
Hello, your code has the file transformers.py, may I ask what it does specifically?I can run the code by deleting this file.

**Comment by wangchen1801** [comment]
Hello yefeng, transforms.py contains some image preprocessing methods. See the file below for more functions. 
```shell
mmfewshot/mmfewshot/detection/datasets/pipelines/transforms.py
```
For example, CropResizeInstance defines how to obtain a fixed-size image patch (224, 224) from the original support image. 
CropResizeInstanceByRatio here does basically the same effect. It is only used in MS COCO dataset and doesn't make a significant difference. So it's ok to delete it and use the CropResizeInstance function as a replacement.

**Comment by yefeng23323** [comment]
你好，就是我在源码中没有找到使用transforms.py的地方，所以直接删除了还是可以正常训练以及测试（只使用VOC数据集）。你说的删除后可用CropResizeInstance函数替代是指什么呢?

**Comment by yefeng23323** [comment]
Hello, it's just that I didn't find a place to use transforms.py in the source code, so you can still train and test normally (using only VOC datasets) by removing it.What do you mean by using CropResizeInstance instead?

**Comment by wangchen1801** [comment]
Hello, transforms.py is only used while training on COCO dataset. Your understanding is correct, we don't need to modify the code. 
Best~
